"use client";
import { useEffect, useState } from "react";
import type { IncidentResult } from "@/lib/types";
import { api } from "@/lib/api";
import { md } from "@/lib/markdown";

interface Props {
  incident: IncidentResult | null;
  zonesDone: Record<string, unknown>;
  executing: string | null;
  onExecute: (action: string) => void;
}

const ZONE_META = [
  { zone: "ZONE1_FREEZE_PREP", action: "FREEZE_PREP", cls: "z1", icon: "⏻", countKey: "PREPARING", unit: "ORDERS IN PREP", btn: "EXECUTE KDS LOCK" },
  { zone: "ZONE2_INTERCEPT_DISPATCH", action: "INTERCEPT_DISPATCH", cls: "z2", icon: "⛔", countKey: "OUT_FOR_DELIVERY", unit: "RIDERS IN TRANSIT", btn: "DISPATCH RIDER HALT" },
  { zone: "ZONE3_NOTIFY_CONSUMER", action: "NOTIFY_CONSUMER", cls: "z3", icon: "📡", countKey: "DELIVERED", unit: "CONSUMERS ALERTED", btn: "TRIGGER SMS WEBHOOK" },
];

export default function Containment({ incident, zonesDone, executing, onExecute }: Props) {
  const [report, setReport] = useState<{ markdown: string; generated_by: string } | null>(null);
  const [reportBusy, setReportBusy] = useState(false);

  useEffect(() => {
    if (!incident) { setReport(null); return; }
    setReportBusy(true);
    api.aiReport(incident.batch_id)
      .then(setReport)
      .catch(() => setReport(null))
      .finally(() => setReportBusy(false));
  }, [incident, zonesDone]);

  if (!incident) {
    return (
      <>
        <div className="panel" style={{ textAlign: "center", color: "var(--ink-faint)", padding: 44 }}>
          Flag a suspect batch and run <b style={{ color: "var(--ink)" }}>blast radius</b> to generate the containment boundary —
          or ask the <b style={{ color: "#d8ccff" }}>AI Copilot</b> to plan it for you.
        </div>
      </>
    );
  }

  const sev = incident.severity_model;

  return (
    <>
      <div className="ai-narrative">
        <div className="an-head">
          <span className="an-badge">◈ AI INCIDENT NARRATIVE</span>
          <span style={{ fontFamily: "var(--font-m)", fontSize: 9, color: "var(--ink-faint)" }}>
            {reportBusy ? "generating…" : report ? `generated by ${report.generated_by}` : ""}
          </span>
          <button
            className="btn-ghost violet"
            style={{ marginLeft: "auto" }}
            onClick={() => { setReportBusy(true); api.aiReport(incident.batch_id).then(setReport).finally(() => setReportBusy(false)); }}
          >
            ↻ REGENERATE
          </button>
        </div>
        <div className="an-body">
          {reportBusy && !report ? <span style={{ color: "var(--ink-faint)" }}>Composing chain-of-custody narrative…</span>
            : report ? <div dangerouslySetInnerHTML={{ __html: md(report.markdown) }} />
            : <span style={{ color: "var(--ink-faint)" }}>Report unavailable.</span>}
        </div>
      </div>

      <div className="contain-head">
        <div className="panel severity-panel">
          <div className="panel-head"><h3>Risk Severity Model</h3><span className="tag danger">DETERMINISTIC</span></div>
          <div className="sev-score" style={{ color: sev.class === "CRITICAL" ? "var(--red-soft)" : "var(--orange)" }}>{sev.score}</div>
          <div className="sev-class">CLASSIFICATION: {sev.class}</div>
          <div className="sev-formula" dangerouslySetInnerHTML={{ __html: `S<sub>bio</sub> × (O<sub>prep</sub>×2.0 + O<sub>transit</sub>×3.0 + O<sub>deliv</sub>×1.5) × C<sub>temp</sub><br>= ${sev.formula} = <b style="color:var(--ink)">${sev.score}</b>` }} />
        </div>
        <div className="panel surgical-panel">
          <div className="panel-head"><h3>Surgical vs Blanket Recall</h3><span className="tag">ROI</span></div>
          <div className="surgical-copy">
            A blanket shutdown discards <b>₹80,000</b> of safe food. TracePulse isolates only the recipes mapped
            via <code>[:USES_BATCH]</code> to the flagged batch — <b className="ok">biryani, dal & breads stay LIVE</b>.
          </div>
          <div className="roi-bars">
            <div className="roi-row"><span className="roi-label">Blanket recall loss</span><div className="roi-track"><div className="roi-fill bad" style={{ width: "100%" }}></div></div><span className="roi-val">₹80.0k</span></div>
            <div className="roi-row"><span className="roi-label">TracePulse loss</span><div className="roi-track"><div className="roi-fill good" style={{ width: "3%" }}></div></div><span className="roi-val ok">≈₹0</span></div>
          </div>
        </div>
      </div>

      <div className="zones">
        {ZONE_META.map((z) => {
          const boundary = incident.containment_boundary.find((b) => b.zone === z.zone);
          const count = incident.status_counts[z.countKey] || 0;
          const done = !!zonesDone[z.action];
          const res = zonesDone[z.action] as Record<string, unknown> | undefined;
          const doneMsg =
            z.action === "FREEZE_PREP" ? `${((res?.locked_kitchens as string[]) || []).length} stations locked · safe lines unaffected` :
            z.action === "INTERCEPT_DISPATCH" ? `${res?.orders_intercepted ?? 0} orders flipped to INTERCEPTED` :
            `${res?.notifications_queued ?? 0} alerts queued via webhook`;
          return (
            <div className={`zone ${z.cls}`} key={z.zone}>
              <div className="zone-top">
                <div>
                  <div className="zone-num">{z.zone.split("_")[0]} · {z.action.replaceAll("_", " ")}</div>
                  <div className="zone-title">{z.icon} {boundary?.title}</div>
                </div>
                <div className="zone-count"><div className="zc-num">{count}</div><div className="zc-l">{z.unit}</div></div>
              </div>
              <div className="zone-desc">{boundary?.desc}</div>
              <div className="zone-directive">{boundary?.directive}</div>
              <button className={`btn-zone ${done ? "done" : ""}`} disabled={done || executing === z.action} onClick={() => onExecute(z.action)}>
                {done ? "✓ EXECUTED" : executing === z.action ? "DISPATCHING…" : z.btn}
              </button>
              <div className={`zone-status ${done ? "ok" : ""}`}>{done ? doneMsg : ""}</div>
            </div>
          );
        })}
      </div>
    </>
  );
}
