"""
FSSAI §28 chain-of-custody incident report.
Template engine always works; if an LLM key is configured, the structured
facts are handed to the model for an inspector-grade narrative (facts unchanged).
"""
from __future__ import annotations

from dataclasses import asdict

import services
from data import INCIDENT

from . import provider


def _facts(g, batch_id: str) -> dict:
    blast = services.blast_radius_data(g, batch_id)
    cross = services.cross_contamination_data(g, batch_id)
    batch = g.find("Batch", batch_id)
    supplier = next((g.nodes[r.start] for r in batch.in_rels if r.type == "SUPPLIED"), None) if batch else None
    warehouse = next((g.nodes[r.end] for r in batch.out_rels if r.type == "STORED_AT"), None) if batch else None
    return {
        "incident": INCIDENT,
        "batch": batch.to_dict() if batch else {},
        "supplier": supplier.to_dict() if supplier else {},
        "warehouse": warehouse.to_dict() if warehouse else {},
        "metrics": blast["metrics"],
        "status_counts": blast["status_counts"],
        "severity": blast["severity"],
        "kitchens": blast["kitchens"],
        "dishes": blast["dishes"],
        "shipments": blast["shipments"],
        "cross_contamination": cross["co_shipped_batches"],
    }


def _template(f: dict) -> str:
    m, sc = f["metrics"], f["status_counts"]
    kit_rows = "\n".join(f"| {k['id']} | {k['name']} | {k['cluster']} | {k['status']} |" for k in f["kitchens"])
    ship_rows = "\n".join(
        f"| {s['id']} | {s['vehicle_plate']} | {s['avg_temp_c']}°C {'⚠ BREACH' if s['avg_temp_c'] > 8 else '✓'} |"
        for s in f["shipments"])
    cross_rows = "\n".join(
        f"| {c['batch_id']} | {c['ingredient']} | {c['shared_shipment']} | {c['temp_c']}°C | {c['status']} |"
        for c in f["cross_contamination"]) or "| — | none | — | — | — |"
    b, sup, wh = f["batch"], f["supplier"], f["warehouse"]
    return f"""# FSSAI INCIDENT REPORT — {f['incident']['id']}
**Generated by TracePulse NCR** · Food Safety & Standards Act, 2006 — §28 traceability
**Classification:** {f['incident']['severity']} · {f['incident']['reason']}

## 1. Chain of Custody
| Hop | Entity | Detail |
|---|---|---|
| Origin | {sup.get('name','—')} | {sup.get('location','—')} · FSSAI lic. {sup.get('fssai_license','—')} |
| Batch | {b.get('id','—')} | {b.get('ingredient_name','')} · mfg {b.get('mfg_date','')} · {b.get('quantity_kg',0)} kg |
| Storage | {wh.get('name','—')} | {wh.get('zone','')} · bay C-14 |
| Transit | {len(f['shipments'])} reefer shipments | see §2 |
| Downstream | {m['affected_kitchens']} kitchens / {m['affected_dishes']} dishes / {m['affected_orders']} orders | {', '.join(m['clusters'])} |

## 2. Transit Temperatures
| Shipment | Vehicle | Avg temp |
|---|---|---|
{ship_rows}

## 3. Blast Radius (deterministic graph traversal)
- Orders affected: **{m['affected_orders']}** — {sc.get('PREPARING',0)} preparing · {sc.get('OUT_FOR_DELIVERY',0)} in transit · {sc.get('DELIVERED',0)} delivered
- Consumers exposed: **{m['exposed_customers']}** · GMV at risk **{services.fmt_inr(m['gmv_at_risk_inr'])}**
- Severity index: **{f['severity']['score']} ({f['severity']['class']})** = {f['severity']['formula']}

## 4. Affected Kitchens
| Kitchen | Name | Cluster | Status |
|---|---|---|---|
{kit_rows}

## 5. Cross-Contamination (shared breached shipment)
| Batch | Ingredient | Shipment | Temp | Status |
|---|---|---|---|---|
{cross_rows}

## 6. Containment Directives Issued
1. **FREEZE_PREP** — paneer SKU lines locked at {m['affected_kitchens']} stations (non-affected lines remained LIVE)
2. **INTERCEPT_DISPATCH** — transit orders flipped to INTERCEPTED pre-handover
3. **NOTIFY_CONSUMER** — safety SMS via SHA-256 phone hashes (no PII in graph)

---
*Report reconstructed from immutable graph edges. Every figure above is a deterministic traversal result, not an estimate.*
"""


def generate(g, batch_id: str) -> dict:
    facts = _facts(g, batch_id)
    markdown = _template(facts)
    cfg = provider.get_config()
    if cfg["enabled"]:
        try:
            import asyncio
            prompt = (
                "You are a food-safety compliance writer. Rewrite the following incident report into a polished "
                "inspector-grade narrative for FSSAI. Keep EVERY number, ID, and fact exactly as given; add no new facts. "
                "Keep markdown headings. Be concise.\n\n" + markdown
            )
            try:
                loop = asyncio.get_running_loop()
            except RuntimeError:
                loop = None
            if loop and loop.is_running():
                # called from sync context inside a running loop (tool executor) — schedule blocking wait
                import concurrent.futures
                with concurrent.futures.ThreadPoolExecutor() as pool:
                    prose = pool.submit(asyncio.run, provider.chat_once(
                        [{"role": "user", "content": prompt}])).result(timeout=60)
            else:
                prose = asyncio.run(provider.chat_once([{"role": "user", "content": prompt}]))
            if prose.strip():
                return {"markdown": prose, "generated_by": f"llm:{cfg['model']}", "facts": facts}
        except Exception:  # noqa: BLE001 — never break the report
            pass
    return {"markdown": markdown, "generated_by": "deterministic-template", "facts": facts}
